version: '3'
services:
  minecraft:
    container_name: minecraft-server
    image: itzg/minecraft-server
    restart: 'unless-stopped'
    ports:
      - "25565:25565"
    volumes:
      - /Users/meganbailey/Minecraft/minecraft-server/data:/data
    healthcheck:
      test: ["CMD", "mc-monitor status" ]
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      DIFFICULTY: "normal"  
      OPS: "xcodegenie"
      DEBUG: true
      DEBUG_MEMORY: true
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      ALLOW_NETHER: true
      MEMORY: 3G
    tty: true
    stdin_open: true